version: "2"

run:
  timeout: 15m

linters:
  default: none
  enable:
    - depguard
    - gocritic
    - goheader
    - ineffassign
    - misspell
    - prealloc
    - staticcheck
    # - typecheck
    - unconvert
    - unparam
    # TODO: Enable these linters
    # - errcheck
    # - goerr113
    # - gosec
  exclusions:
    paths:
      - ^.*\.(pb|y)\.go$
      - "vendor"
    rules:
      - linters:
          - staticcheck
        text: "SA1019"
  settings:
    depguard:
      rules:
        std-packages:
          list-mode: original
          deny:
            - pkg: "sync/atomic"
              desc: "Use go.uber.org/atomic instead of sync/atomic."
            - pkg: "io/ioutil"
              desc: "Use corresponding 'os' or 'io' functions instead."
        sdk-over-pipecd:
          list-mode: original
          files:
            - "plugins/**/*.go"
          deny:
            - pkg: "github.com/pipe-cd/pipecd/pkg/config$" # TODO: update to SDK
              desc: "Use github.com/pipe-cd/pipecd/pkg/configv1 instead."
            # TODO: deny sdk dir, use piped-plugin-sdk-go
    gocritic:
      disabled-checks:
        - appendAssign
    goheader:
      values:
        regexp:
          any-year: \d{4} # the year of copyright means the first published year, so it can be any year.
      # template does not contains the comment indicator '//' or '/*' '*/'
      template: |-
        Copyright {{any-year}} The PipeCD Authors.

        Licensed under the Apache License, Version 2.0 (the "License");
        you may not use this file except in compliance with the License.
        You may obtain a copy of the License at

            http://www.apache.org/licenses/LICENSE-2.0

        Unless required by applicable law or agreed to in writing, software
        distributed under the License is distributed on an "AS IS" BASIS,
        WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
        See the License for the specific language governing permissions and
        limitations under the License.

formatters:
  enable:
    - gofmt
    - goimports
  settings:
    goimports:
      local-prefixes:
        - github.com/pipe-cd/community-plugins
