name: build

on:
  workflow_dispatch:
  push:
    branches:
      - main
    # tags:
      # - 'v*'
  pull_request:
    branches:
      - main
      # - 'release-v*'

env:
  GO_VERSION: 1.24.3

jobs:
  go:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v4
        with:
          go-version: ${{ env.GO_VERSION }}
          cache: true
      - name: Build go plugins # TODO: Make it parallel
        run: make build/go
      - name: Upload plugin artifacts
        uses: actions/upload-artifact@v4
        with:
          name: pipecd-plugins
          path: .artifacts/plugins/
          retention-days: 7
