name: test

on:
  push:
    branches:
      - main
    # tags:
      # - 'v*'
  pull_request:
    branches:
      - main
      # - 'release-v*'

env:
  GO_VERSION: 1.24.3

jobs:
  list-go-modules:
    runs-on: ubuntu-24.04
    outputs:
      modules: ${{ steps.list-go-modules.outputs.modules }}
    steps:
      - uses: actions/checkout@v4
      - name: List go modules
        id: list-go-modules
        run: |
          echo "modules=$(find . -name go.mod -exec dirname {} \; | sort | jq -R -s -c 'split("\n") | map(select(length > 0))')" >> $GITHUB_OUTPUT

  go:
    runs-on: ubuntu-latest-8-cores
    needs: list-go-modules
    strategy:
      fail-fast: false
      matrix:
        module: ${{ fromJSON(needs.list-go-modules.outputs.modules) }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v4
        with:
          go-version: ${{ env.GO_VERSION }}
          cache: true
      - name: Run unit tests
        run: make test/go PLUGINS=${{ matrix.module }} # COVERAGE=true
      # TODO: Add coverage reporting
      # - name: make flag
      #   id: make-flag
      #   run: |
      #     echo "flags=$(echo ${{ matrix.module }} | tr '/' '-')" >> $GITHUB_OUTPUT
      # - name: Upload coverage reports to Codecov
      #   uses: codecov/codecov-action@v3
      #   with:
      #     flags: ${{ steps.make-flag.outputs.flags }}
      #   env:
      #     CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}

# This job is used to check for the branch protection rules.
  go-test-completed:
    runs-on: ubuntu-24.04
    needs: go
    steps:
      - run: |
          echo completed
